name: Andrew Lackey
favicon: null
layout_spectrum: 0.4182167248800397
typography_spectrum: 0.15197255765087903
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9233577842824161
  lightness: 0.5101579097099602
  saturation: 0.17531807045452297
  rhythmicContrast: 0.5494967524427921
purpose: []
